### ISSUE TITLE
Module Odomter reporting different value

### ISSUE THREAD

**Issue by natrlhy** [denverquane/MMM-Teslamate#16]
MMM-Teslamate is reporting my odometer/mileage to be 2 miles off of what Teslamate reports (9138 on Teslamate and MMM-Teslamate is showing 9140).
Why would this be and does MMM-Teslamate store information that is inaccurate?

**Comment by olexs** [comment]
Could be a rounding error for mi-km conversion. I'm not sure whether the Tesla API reports the odometer reading in metric or imperial, and at which points conversions happen (TeslaMate itself reading the API data, TeslaMate publishing to MQTT, and MMM- TeslaMate reading from MQTT are all possible conversion points), but if the conversion constant is not exactly the same everywhere (it could be 1.6, 1.609 or 1.60934, depending on the precision the developer wanted at the time...) there might be a minor error introduced in the end result.

Important note though: MMM-TeslaMate does not store or calculate this data, it only takes the reading that's published to MQTT by TeslaMate itself. TeslaMate _does_ store the data, but originally it's always taken from the API response from Tesla itself. So even if there is an error, it will not accumulate and get worse over time - on the opposite, if there actually _is_ an error and it's fixed in a future release, the displayed value will be corrected at that point.

**Comment by natrlhy** [comment]
Hi.

I wanted to contribute and make a small change to the MMM-Teslamate.js. I haven't ever do an PR on GitHub or anything so I'd like to see how this is done or be given permission to do this.
Basically I'd like to modify the km to mi conversion number and submit that so I can get a better understanding of all this coding/contributing stuff ;)
Thanks!

**Comment by olexs** [comment]
Sure, you can submit a PR at any time. 

The simplest way for minor changes is just to go to the relevant file in this repository in Github, hit the "Edit this file in your fork of this project" button, and make the change in the web editor. It will be committed to your fork, and Github will offer to create a PR to the base repository right there, guiding you through the process.

Alternatively you can fork the project, clone your fork locally, make and the necessary changes on your machine, then commit and push the changes to your fork. You can do so on a branch of your choosing, or directly on your `master`. After you've pushed the changes, you can navigate to your fork in Github, and it will show "this fork is 1 commit ahead of upstream, create pull request?" and guide you through the rest of the process from there.

**Comment by natrlhy** [comment]
@olexs 

I think I've got it! I'm trying to use VS Code and had to get some github integration setup, but I had to fork the project from github.com and cloned it within VS Code. I've submitted the PR. Now do we just wait for it to be reviewed and committed to the original master?

**Comment by olexs** [comment]
Solved with #20.
