### ISSUE TITLE
Teslamate server not working

### ISSUE THREAD

**Issue by PierreGodetobii** [denverquane/MMM-Teslamate#21]
I have been having MMM-Teslamate working fine om a PI 3 for a year soon. and now updated to a Pi 4

so I do the whole clone of MMM-Teslamate and npm install and then docker setup and the docker-compose up -d
and get.
CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS                    NAMES
0d5a1ef0da8d        teslamate/teslamate:latest   "/sbin/tini -- /bin/…"   About a minute ago   Up 29 seconds       0.0.0.0:4000->4000/tcp   pi_teslamate_1
528fc54e9a7b        postgres:13                  "docker-entrypoint.s…"   About a minute ago   Up 5 seconds        5432/tcp                 pi_database_1
e366ab79311a        teslamate/grafana:latest     "/run.sh"                About a minute ago   Up 29 seconds       0.0.0.0:3000->3000/tcp   pi_grafana_1
689c4224a5e1        eclipse-mosquitto:1.6        "/docker-entrypoint.…"   About a minute ago   Up 29 seconds       0.0.0.0:1883->1883/tcp   pi_mosquitto_1

Looking good. then I go to my browser and test http://192.168.1.179:3000/ and yes Grafana works.
then I test http://192.168.1.179:4000 and I get no response.
beating my self up here. tried with docker rm -vf $(docker ps -a -q) and docker-compose up -d 
but same. grafana works but not teslamate. I also tried on the pi itself with localhost:4000.

please help.

**Comment by olexs** [comment]
Sounds like your issues is not with MMM-Teslamate but with TeslaMate itself. You should post an issue there (https://github.com/adriankumpf/teslamate) - this project is only for the MagicMirror plugin, and cannot help with issues related to TeslaMate itself not working properly.

But a hint nevertheless: if Teslamate was has updated versions since you last pulled the images, it might take it a while to start up after you pull a fresh version, because it needs to run multiple database migrations to bring the schema up to date. Try running `docker-compose logs -f` to see if/what the containers are doing. Database migrations between versions of TeslaMate can take several minutes, and the UI only starts up on port 4000 after those are done.

**Comment by PierreGodetobii** [comment]
> Sounds like your issues is not with MMM-Teslamate but with TeslaMate itself. You should post an issue there (https://github.com/adriankumpf/teslamate) - this project is only for the MagicMirror plugin, and cannot help with issues related to TeslaMate itself not working properly.
> 
> But a hint nevertheless: if Teslamate was has updated versions since you last pulled the images, it might take it a while to start up after you pull a fresh version, because it needs to run multiple database migrations to bring the schema up to date. Try running `docker-compose logs -f` to see if/what the containers are doing. Database migrations between versions of TeslaMate can take several minutes, and the UI only starts up on port 4000 after those are done.

Oh great! thank you!
