### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by husoseli15** [denverquane/MMM-Teslamate#29]
I'm getting a black screen on my MM whenever I add MMM-TeslaMate to the config file. 

Any idea why this would be happening?

**Comment by olexs** [comment]
Sounds like something in your config for the module is causing the MagicMirror to crash. Could you please post your config (of course, removing/obscuring any passwords or keys as necessary)?

Also, have you ran "npm install" in the MMM-Teslamate module folder when installing it?

**Comment by husoseli15** [comment]
Hey Olex,

I've attached config file for you to take a look at. I ran NPM install in MMM-Teslamate. Not sure sure what would be causing this problem, as I'm not getting any errors from the logs.
[configjs.txt](https://github.com/denverquane/MMM-Teslamate/files/8017943/configjs.txt)

**Comment by olexs** [comment]
You have set the MMM-Teslamate module position to `top-center` on line 65. That could be an issue because 

a) that's spelled wrong, correct value would be `top_center` (underscore instead of dash), and 
b) you also have MMM-Ring occupying the same slot, not sure the top center slot can be used by multiple modules at ones - though I may be mistaken there.

Config looks good otherwise, so try changing that and see if it fixes the issue. If not, I may try to start up an instance with your config and see if the logs and debug output are any help.

**Comment by husoseli15** [comment]
Oh man I feel so silly. It was the top-center that was causing the black screen :/ thank you much!

**Comment by olexs** [comment]
No problem, glad to help :) Thanks for posting your config and making the debug easy!
